env:
  global:
    - LC_CTYPE=en_US.UTF-8
before_install:
  - brew update
  - brew install swiftlint
matrix:
  include:
    - os: osx
      language: objective-c
      osx_image: xcode7.3
      script:
        - swiftlint
        - xcodebuild test -project CustomKeyboardTextField.xcodeproj -scheme CustomKeyboardTextFieldTests -destination 'platform=iOS Simulator,name=iPhone 6s' | xcpretty -c      
      after_success:
        - bash <(curl -s https://codecov.io/bash) -J 'CustomKeyboardTextField' 
    - os: osx
      language: objective-c
      osx_image: xcode7.3
      script: 
        - xcodebuild build -project CustomKeyboardTextField.xcodeproj -scheme CustomKeyboardTextFieldDemo -destination 'platform=iOS Simulator,name=iPhone 6s' | xcpretty -c      
